### ISSUE TITLE
Request for Sample Guide

### ISSUE THREAD

**Issue by kyilintun2017** [samb1729/SteamAuthDotNet#2]
Dear @sambooo ,
             I have try your source code. But got some difficulties when running the application. Would you kindly help me with the issue.
1. About Application Key in Startup.cs
        As inside the source code the configuration has been removed. I replace webconfig declaration with just the WebAPI key from steam.
Eg,   
            
var key = "MyApiKeyIssuedFromSteam";            
var options = new SteamAuthenticationOptions
            {
                ApplicationKey = key
           };
              
2. AuthenticatedResult is null in HomeController's Index.
       I have debug this stage.
 
var authenticateResult =
                await HttpContext.GetOwinContext().Authentication.AuthenticateAsync("ExternalCookie");

3. Return url of ChallengeResult
             When i call the ChallengeResult from AuthoriseSteam() of HomController. the return is route to 
               [Localhost]/Home/AuthoriseSteam.

Did I miss out any declaration. Could you guide me with more info? Thanks.

Best Regards,
KYI LIN TUN

**Comment by kyilintun2017** [comment]
will not use this project. Fund other way.

**Comment by AleksaDjordjic** [comment]
> 
> 
> will not use this project. Fund other way.

Can you tell us what that other way is maybe...?
